version: "3"
services:
     jenkins:
        build: .
        ports:
        - "8081:8080"
     gitlab:
        image: gitlab/gitlab-ce:latest
        hostname: hostname
        environment:
              GITLAB_OMNIBUS_CONFIG: |
               gitlab_rails['gitlab_shell_ssh_port'] = 8822
        ports:
        - "1443:443"
        - "8880:80"
        - "8822:22"
# The logs directory can be mapped to the logs directory in the same director
# as the docker-compose file using the following entry under volumes:
# - ./logs:/var/log/gitlab
        restart: always
     nexus:
         image: sonatype/nexus3
         ports:
         - "8083:8081"